# Generated by Django 5.2.8 on 2025-11-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
